### ISSUE TITLE
1.16 Update Progress

### ISSUE THREAD

**Issue by codehz** [codehz/ElementZero#99]
- [x] Audit
- [x] Basic Anti Cheat
- [x] Blacklist
- [x] Bossbar Support
- [x] Bus 
- [x] Chat API
- [x] Command Support
- [x] Crash Handler
- [x] Custom Scoreboard
- [x] Debug Tool
- [x] Dynamic Motd
- [x] Economy
- [x] Essentials
- [x] Experimental
- [x] Flat World
- [x] Network Status
- [x] No Encryption
- [x] Null Player Data
- [x] Packet Dumper
- [x] Script Support
- [ ] ~~Sign Command~~
- [x] Spawn Protection

**Comment by ambiennt** [comment]
for those of you who dont know, getting a flat world can be achieved in the vanilla BDS by adding this to your server.properties file:

level-type=FLAT
#FLAT, LEGACY, or DEFAULT (has to be in caps)

**Comment by plutonium777** [comment]
@nrss Wow, thx

**Comment by codehz** [comment]
@nrss Actually this mod is to define flat world config (like TNT at 0 layer  etc

**Comment by ambiennt** [comment]
> @nrss Actually this mod is to define flat world config (like TNT at 0 layer etc

ah, I see. That sounds even cooler, I always would welcome more customization options :)

**Comment by codehz** [comment]
> > @nrss Actually this mod is to define flat world config (like TNT at 0 layer etc
> 
> ah, I see. That sounds even cooler, I always would welcome more customization options :)

as demo

![image](https://user-images.githubusercontent.com/13158903/85545480-8f884c00-b64e-11ea-97f1-bc90d4c38cb9.png)

**Comment by Weissnix4711** [comment]
@codehz So basically it's like what we have in Java Edition? I presume you change the settings in custom.yaml?

Btw, I tried running eac056940a64122b670838f70bcbd99b45272215 but it crashes, without mods enabled. Is it just me?

Edit: I see your next commit built. I'll try it.

**Comment by codehz** [comment]
> Btw, I tried running [eac0569](https://github.com/Element-0/ElementZero/commit/eac056940a64122b670838f70bcbd99b45272215) but it crashes, without mods enabled. Is it just me?

So did you have the crash log?

**Comment by elijahr2411** [comment]
Thank you for this amazing modded server software! I fully support you and what you are doing.

**Comment by Weissnix4711** [comment]
> > Btw, I tried running [eac0569](https://github.com/Element-0/ElementZero/commit/eac056940a64122b670838f70bcbd99b45272215) but it crashes, without mods enabled. Is it just me?
> 
> So did you have the crash log?

Nope, sorry. Tried a later commit and it runs fine. So I'm not sure what happened, but it's fixed now, so 🤷‍♂️. Looking at your commits, not even sure how it fixed the issue. But it did, so I'm not complaining.

If I get another crash, I'll make sure to upload the log.

**Comment by elijahr2411** [comment]
Is sign command being removed? I'm just confused because its crossed out.

**Comment by Seggie1313** [comment]
> Is sign command being removed? I'm just confused because its crossed out.

(Sign command still not working, don't enable it)
That's what he said on the prerelease. It just isn't working. Lol

**Comment by Shanwer** [comment]
#135 
How to read audit results?
